name: movie_guide
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  json_annotation: ^4.0.1
  cupertino_icons: ^1.0.2
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^4.1.4

flutter:
  uses-material-design: true 
